[package]
name = "glob-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
glob = "0.3.2"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.96"
syn-mid = { version = "0.6.0", features = ["clone-impls"] }
